version: "3.2"
services:
  ftp-server:
    restart: always
    image: ftp-server
    container_name: ftp-server
    volumes:
    - /opt/resource/:/home/resource
    environment:
      TZ: Asia/Shanghai
    ports:
    - 2221:2221
    - 10000-10500:10000-10500

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    environment:
    - TZ=Asia/Shanghai
    ports:
    - 80:80
    - 443:443
    volumes:
    - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /opt/nginx/conf.d:/etc/nginx/conf.d
    - /opt/nginx/html:/usr/share/nginx/html
    - /opt/nginx/log:/var/log/nginx
    - /etc/letsencrypt:/etc/letsencrypt
